---

host: "localhost"
root_login: "root"
root_pass: "123456"
old_pass: "123456"

ssh_known_hosts_command: "ssh-keyscan -H -T 10"
ssh_known_hosts_file: "/etc/ssh/ssh_known_hosts"
ssh_known_hosts:
  - github.com
  - bitbucket.org

#example  
#- {
#     name: "test.local",
#     local_path: "/projects/test.local",
#     virtual_path: "/var/www/test.local",
#     webroot: "/var/www/test.local",
#     database: "test_local",
#     git_repo: "test-local.git"
#   }

projects: 