---

#network settings
private_network: "192.168.33.77"
forwarded_port_guest: "4747"
forwarded_port_host: "4747"

#path to id_rsa key
id_rsa_path: "/path/to/id_rsa"

#mysql credentials
host: "localhost"
root_login: "root"
root_pass: "123456"
old_pass: "123456"

ssh_known_hosts_command: "ssh-keyscan -H -T 10"
ssh_known_hosts_file: "/etc/ssh/ssh_known_hosts"
ssh_known_hosts:
  - github.com
  - bitbucket.org

#packages settings
node_version: "7.x"

#projects data example, add to projects:
#- {
#     name: "test.loc",
#     local_path: "/Users/admin/projects/test.loc",
#     virtual_path: "/var/www/test.loc",
#     webroot: "/var/www/test.loc",
#     database: "test_local",
#     git_repo: "git@github.com:admin/test.git" (or hg_repo)
#   }
projects: