---

#network settings
private_network: "192.168.33.77"
forwarded_port_guest: "4747"
forwarded_port_host: "4747"

#path to id_rsa key
id_rsa_path: "/path/to/id_rsa"

#mysql credentials
host: "localhost"
root_login: "root"
root_pass: "123456"
old_pass: "123456"

ssh_known_hosts_command: "ssh-keyscan -H -T 10"
ssh_known_hosts_file: "/etc/ssh/ssh_known_hosts"
ssh_known_hosts:
  - github.com
  - bitbucket.org

#packages settings
node_version: "7.x"

#projects data example, add to projects:
#- {
#     name: "test.loc", (required)
#     local_path: "/Users/admin/projects/test.loc", (required)
#     virtual_path: "/var/www/test.loc", (required)
#     webroot: "/var/www/test.loc", (required)
#     database: "test_loc", (optional, if exist create mysql database)
#     git_repo: "git@github.com:admin/test.git" (or hg_repo, optional, if exist clone project)
#     proxy_port: "8080" (optional, proxy from this port to test.loc in browser)
#   }
projects: