---

- name: start Mysql service
  service: name=mysql state=started enabled=true
  
- name: Set root user password
  mysql_user: 
    name=root
    host="{{ host }}"
    password="{{ root_pass }}"
    check_implicit_admin=yes
    login_user="{{ root_login }}"
    login_password="{{ old_pass }}"
    state=present
  
- name: create a new database
  mysql_db:
    login_user="{{ root_login }}"
    login_password="{{ root_pass }}"
    name={{ item.database }}
    state=present
    collation=utf8_general_ci
  with_items: "{{ projects }}"
  when: item.database is defined